[package]
name = "zaoai-types"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
humantime-serde = "1.1.1"
regex = "1.11.1"
serde = "1.0.219"
serde-xml-rs = "0.8.1"
serde_json = "1.0.141"
tempfile = "3.20.0"
